AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with Docker to host Optimy
Resources:
  OptimyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0 # Amazon Linux 2 AMI (for example)
      KeyName: your-key-pair
      SecurityGroups:
      - !Ref OptimySecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install docker -y
          service docker start
          usermod -a -G docker ec2-user
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          git clone https://github.com/yourusername/optimy.git
          cd optimy
          docker-compose up -d

  OptimySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
