global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]

- job_name: 'cadvisor'
  static_configs:
  - targets: [ 'cadvisor:8080' ]

remote_write:
- url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
  basic_auth:
    username: ID
    password: KEY
